import {StyleSheet} from 'react-native';
import {colors} from '../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    backgroundColor: colors.primary,
    padding: 24,
    paddingTop: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomRightRadius: 32,
    borderBottomLeftRadius: 32,
    position: 'relative',
  },
  greeting: {
    flex: 1,
  },
  greetingText: {
    fontFamily: 'DMSans',
    color: '#fff',
    fontSize: 14,
  },
  userName: {
    fontFamily: 'BebasNeue-Regular',
    color: '#fff',
    fontSize: 24,
  },
  avatarBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  points: {
    flexDirection: 'row',
    borderRadius: 6,
    backgroundColor: colors.primary600,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: 'center',
  },
  pointsText: {
    fontSize: 16,
    fontFamily: 'DMSans',
    color: '#fff',
    marginLeft: 4,
  },
  avatar: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#ccc',
  },
  section: {
    paddingHorizontal: 24,
    marginTop: 50,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 16,
  },
  sectionTitle: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 28,
    color: colors.title,
  },
  card: {
    marginBottom: 24,
  },
  activityBlock: {
    width: '90%',
    alignSelf: 'center',
  },
  activityImage: {
    width: '100%',
    height: 160,
    borderRadius: 8,
  },
  lockIcon: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: colors.primary,
    width: 28,
    height: 28,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardTitle: {
    fontFamily: 'DMSans',
    fontSize: 16,
    marginTop: 16,
    marginBottom: 12,
    color: colors.title,
  },
  cardInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  infoText: {
    fontSize: 12,
    fontFamily: 'DMSans',
    color: colors.title,
    marginHorizontal: 4,
  },
  separator: {
    marginHorizontal: 8,
    fontSize: 14,
    fontFamily: 'DMSans',
    color: colors.title,
  },
  categorySection: {
    paddingHorizontal: 24,
    marginTop: 20,
    marginBottom: 80,
  },
  categoryItem: {
    alignItems: 'center',
    marginRight: 24,
  },
  categoryText: {
    marginTop: 8,
    fontFamily: 'DMSans',
    fontSize: 16,
    color: colors.title,
  },
  floatingButton: {
    position: 'absolute',
    right: 32,
    bottom: 32,
    backgroundColor: colors.primary,
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
  },
  circleSmall: {
    position: 'absolute',
    top: -40,
    left: -40,
    width: 150,
    height: 150,
    borderRadius: 150,
    backgroundColor: '#fff',
    opacity: 0.1,
    zIndex: 0,
  },
  circleLarge: {
    position: 'absolute',
    top: -80,
    left: -80,
    width: 240,
    height: 240,
    borderRadius: 240,
    backgroundColor: '#fff',
    opacity: 0.1,
    zIndex: 0,
  },
});
