import {StyleSheet} from 'react-native';
import {colors} from '../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    paddingHorizontal: 24,
    paddingTop: 0,
    justifyContent: 'center',
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 80,
    marginBottom: 40,
  },
  iconCircle: {
    backgroundColor: colors.primary,
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  logoText: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 28,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    color: colors.title,
  },
  title: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 32,
    color: colors.title,
    marginBottom: 14,
    textAlign: 'left',
    alignSelf: 'flex-start',
  },
  subtitle: {
    fontFamily: 'DMSans-Regular',
    fontSize: 16,
    color: colors.text,
    marginBottom: 24,
    textAlign: 'left',
    alignSelf: 'flex-start',
  },
  label: {
    fontFamily: 'DMSans-SemiBold',
    fontSize: 16,
    color: colors.title,
    marginBottom: 4,
    alignSelf: 'flex-start',
  },
  required: {
    color: colors.warning,
  },
  input: {
    borderWidth: 1,
    borderColor: '#e5e5e5',
    borderRadius: 8,
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontFamily: 'DMSans-Regular',
    fontSize: 14,
    color: colors.text,
  },
  button: {
    marginTop: 24,
    backgroundColor: colors.primary,
    paddingVertical: 0,
    justifyContent: 'center',
    alignItems: 'center',
    height: 44,
    borderRadius: 8,
  },
  buttonText: {
    fontFamily: 'DMSans-Bold',
    fontSize: 16,
    height: 24,
    lineHeight: 24,
    color: '#fff',
    fontWeight: 'bold',
  },
  footerText: {
    marginTop: 20,
    fontFamily: 'DMSans-Regular',
    fontSize: 14,
    color: colors.text,
    textAlign: 'center',
  },
  linkText: {
    fontFamily: 'DMSans-Bold',
    fontSize: 14,
    color: colors.title,
    textDecorationLine: 'none',
  },
  image: {
    width: 28,
    height: 28,
  },
});
