services:
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - "3008:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: full-stack-db
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    container_name: fullstack-api
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma db seed &&
             npm run dev"
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY: test
      AWS_SECRET_ACCESS_KEY: test
      DATA_DIR: /var/lib/localstack/data
    volumes:
      - localstack-data:/var/lib/localstack/data
    restart: unless-stopped
volumes:
  pgdata:
  localstack-data: